server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/image?serverTimezone=UTC
    username: root
    password: yin7372175240000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:C:/pig/,classpath:/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
mybatis:
  type-aliases-package: com.yaolong.my_blog.entity
  configuration:

    map-underscore-to-camel-case: true
logging:
  level:
    com.example.springboot_cache.mapper: debug